name: Maven Build & Test

on:
  push:
    branches:
      - main  # Asume que estás usando la rama 'main'. Cambia a 'master' si es necesario.
  pull_request:
    branches:
      - main  # Asume que estás usando la rama 'main'. Cambia a 'master' si es necesario.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'  # Aquí configuramos para Java 17

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven Build & Test
        run: mvn clean test